/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/spider_webs.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function SpiderWebs(props) {
  const { nodes, materials } = useGLTF("/models/spider_webs.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01} position={[-2, 0, 0]}>
        {/* <mesh
          geometry={nodes.SM_Cobwebs_06_Cobwebs_M_0.geometry}
          material={materials.Cobwebs_M}
        />
        <mesh
          geometry={nodes.SM_Cobwebs_14_Cobwebs_M_0.geometry}
          material={materials.Cobwebs_M}
        />
        <mesh
          geometry={nodes.SM_Cobwebs_12_Cobwebs_M_0.geometry}
          material={materials.Cobwebs_M}
        />
        <mesh
          geometry={nodes.SM_Cobwebs_08_Cobwebs_M_0.geometry}
          material={materials.Cobwebs_M}
        />
        <mesh
          geometry={nodes.SM_Cobwebs_09_Cobwebs_M_0.geometry}
          material={materials.Cobwebs_M}
        />
        <mesh
          geometry={nodes.SM_Cobwebs_01_Cobwebs_M_0.geometry}
          material={materials.Cobwebs_M}
        /> */}
        <mesh
          castShadow
          geometry={nodes.SM_Cobwebs_05_Cobwebs_M_0.geometry}
          material={materials.Cobwebs_M}
        />
        {/* <mesh
          geometry={nodes.SM_Cobwebs_04_Cobwebs_M_0.geometry}
          material={materials.Cobwebs_M}
        />
        <mesh
          geometry={nodes.SM_Cobwebs_03_Cobwebs_M_0.geometry}
          material={materials.Cobwebs_M}
        />
        <mesh
          geometry={nodes.SM_Cobwebs_15_Cobwebs_M_0.geometry}
          material={materials.Cobwebs_M}
        />
        <mesh
          geometry={nodes.SM_Cobwebs_16_Cobwebs_M_0.geometry}
          material={materials.Cobwebs_M}
        />
        <mesh
          geometry={nodes.SM_Cobwebs_07_Cobwebs_M_0.geometry}
          material={materials.Cobwebs_M}
        />
        <mesh
          geometry={nodes.SM_Cobwebs_13_Cobwebs_M_0.geometry}
          material={materials.Cobwebs_M}
        />
        <mesh
          geometry={nodes.SM_Cobwebs_10_Cobwebs_M_0.geometry}
          material={materials.Cobwebs_M}
        />
        <mesh
          geometry={nodes.SM_Cobwebs_11_Cobwebs_M_0.geometry}
          material={materials.Cobwebs_M}
        />
        <mesh
          geometry={nodes.SM_Cobwebs_02_Cobwebs_M_0.geometry}
          material={materials.Cobwebs_M}
        /> */}
      </group>
    </group>
  );
}

useGLTF.preload("/models/spider_webs.glb");
