/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/plane.glb 
Author: Stéphane Agullo (https://sketchfab.com/sa3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/boeing-stearman-model-75-57035fcd89e7496aa712ca1b522700fd
Title: BOEING-STEARMAN MODEL 75
*/

import React, { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function PlaneModel(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF("/models/plane.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions["Base Stack"]) {
      actions["Base Stack"].reset().fadeIn(0.5).play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="78a3344d6a74474ea9bccd9356bf38fafbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="avion_DEF5Layer2"
                  position={[0, 0, -8376.507]}
                  scale={[0.2, 0.2, 0.3]}
                >
                  <mesh
                    name="avion_DEF5Layer2_NUAGES_0"
                    geometry={nodes.avion_DEF5Layer2_NUAGES_0.geometry}
                    material={materials.NUAGES}
                  />
                </group>
                <group
                  name="avion_DEF5Layer3_(1)"
                  position={[0, 0, -9023.669]}
                  scale={[0.3, 0.4, 0.3]}
                >
                  <mesh
                    name="avion_DEF5Layer3_(1)_PLUIE_0"
                    geometry={nodes["avion_DEF5Layer3_(1)_PLUIE_0"].geometry}
                    material={materials.PLUIE}
                  />
                </group>
                <group
                  name="avion_DEF5Layer3_(2)"
                  position={[0, 0, -8861.25]}
                  rotation={[0, 0, -2.691]}
                  scale={[0.3, 0.4, 0.3]}
                >
                  <mesh
                    name="avion_DEF5Layer3_(2)_PLUIE_0"
                    geometry={nodes["avion_DEF5Layer3_(2)_PLUIE_0"].geometry}
                    material={materials.PLUIE}
                  />
                </group>
                <group
                  name="avion_DEF5Layer3_(3)"
                  position={[0, 0, -9053.272]}
                  rotation={[0, 0, 1.166]}
                  scale={[0.3, 0.4, 0.3]}
                >
                  <mesh
                    name="avion_DEF5Layer3_(3)_PLUIE_0"
                    geometry={nodes["avion_DEF5Layer3_(3)_PLUIE_0"].geometry}
                    material={materials.PLUIE}
                  />
                </group>
                <group
                  name="avion_DEF5Layer3_(4)"
                  position={[0, 0, -8861.25]}
                  rotation={[0, 0, -1.443]}
                  scale={[0.3, 0.4, 0.3]}
                >
                  <mesh
                    name="avion_DEF5Layer3_(4)_PLUIE_0"
                    geometry={nodes["avion_DEF5Layer3_(4)_PLUIE_0"].geometry}
                    material={materials.PLUIE}
                  />
                </group>
                <group name="cam" position={[0, 10.224, -91.157]} />
                <group name="TOT_(1)">
                  <group
                    name="avion_DEF5corps_(1)"
                    rotation={[-0.001, -0.001, 0]}
                  >
                    <group name="avion_DEF5elice_(1)" rotation={[0, 0, -2.095]}>
                      <mesh
                        name="avion_DEF5elice_(1)_fer_elices2_0"
                        geometry={
                          nodes["avion_DEF5elice_(1)_fer_elices2_0"].geometry
                        }
                        material={materials.fer_elices2}
                      />
                      <mesh
                        name="avion_DEF5elice_(1)_black_0"
                        geometry={nodes["avion_DEF5elice_(1)_black_0"].geometry}
                        material={materials.black}
                      />
                    </group>
                    <group name="avion_DEF5aileron-AR-vert_(1)">
                      <mesh
                        name="avion_DEF5aileron-AR-vert_(1)_AVION_0"
                        geometry={
                          nodes["avion_DEF5aileron-AR-vert_(1)_AVION_0"]
                            .geometry
                        }
                        material={materials.AVION}
                      />
                    </group>
                    <group
                      name="avion_DEF5aileron-AR-ga_(1)"
                      position={[0, -22.96, 1.776]}
                      rotation={[-0.048, 0, 0]}
                    >
                      <mesh
                        name="avion_DEF5aileron-AR-ga_(1)_AVION_0"
                        geometry={
                          nodes["avion_DEF5aileron-AR-ga_(1)_AVION_0"].geometry
                        }
                        material={materials.AVION}
                      />
                    </group>
                    <group
                      name="avion_DEF5aileron-AR-dr_(1)"
                      position={[0, -8.521, 0.531]}
                      rotation={[-0.018, 0, 0]}
                    >
                      <mesh
                        name="avion_DEF5aileron-AR-dr_(1)_AVION_0"
                        geometry={
                          nodes["avion_DEF5aileron-AR-dr_(1)_AVION_0"].geometry
                        }
                        material={materials.AVION}
                      />
                    </group>
                    <group
                      name="avion_DEF5aileron-AV-bas-ga_(1)"
                      position={[0, 0.485, -2.965]}
                      rotation={[-0.048, 0, 0]}
                    >
                      <mesh
                        name="avion_DEF5aileron-AV-bas-ga_(1)_AVION_0"
                        geometry={
                          nodes["avion_DEF5aileron-AV-bas-ga_(1)_AVION_0"]
                            .geometry
                        }
                        material={materials.AVION}
                      />
                    </group>
                    <group
                      name="avion_DEF5aileron-AV-bas-dr_(1)"
                      position={[0, 0.196, -1.098]}
                      rotation={[-0.018, 0, 0]}
                    >
                      <mesh
                        name="avion_DEF5aileron-AV-bas-dr_(1)_AVION_0"
                        geometry={
                          nodes["avion_DEF5aileron-AV-bas-dr_(1)_AVION_0"]
                            .geometry
                        }
                        material={materials.AVION}
                      />
                    </group>
                    <group name="avion_DEF5aileron-AV-haut-ga_(1)">
                      <mesh
                        name="avion_DEF5aileron-AV-haut-ga_(1)_AVION_0"
                        geometry={
                          nodes["avion_DEF5aileron-AV-haut-ga_(1)_AVION_0"]
                            .geometry
                        }
                        material={materials.AVION}
                      />
                    </group>
                    <group name="avion_DEF5Layer11_(1)">
                      <mesh
                        name="avion_DEF5Layer11_(1)_AVION_0"
                        geometry={
                          nodes["avion_DEF5Layer11_(1)_AVION_0"].geometry
                        }
                        material={materials.AVION}
                      />
                    </group>
                    <mesh
                      name="avion_DEF5corps_(1)_AVION_0"
                      geometry={nodes["avion_DEF5corps_(1)_AVION_0"].geometry}
                      material={materials.AVION}
                    />
                    <mesh
                      name="avion_DEF5corps_(1)_VERRE_0"
                      geometry={nodes["avion_DEF5corps_(1)_VERRE_0"].geometry}
                      material={materials.VERRE}
                    />
                    <mesh
                      name="avion_DEF5corps_(1)_PERSOS_0"
                      geometry={nodes["avion_DEF5corps_(1)_PERSOS_0"].geometry}
                      material={materials.PERSOS}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/plane.glb");
