/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/spider.glb 
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function SpiderModels(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("models/spider.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="f4c7dff2b8264fc5bf6d28e22753d2d4fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <group name="Object_5" />
                  <group name="bones_01">
                    <primitive object={nodes.body_02} />
                  </group>
                  <group name="Spider" />
                  <group name="pPlane1">
                    <mesh
                      name="pPlane1_Camera_lambert2_0"
                      geometry={nodes.pPlane1_Camera_lambert2_0.geometry}
                      material={materials.Camera_lambert2}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
          <skinnedMesh
            name="Object_6"
            geometry={nodes.Object_6.geometry}
            material={materials.Spider_M}
            skeleton={nodes.Object_6.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/spider.glb");
